module.exports = {
  apps: [
    {
      name: 'buizz-api',
      script: 'server.js',
      cwd: '/opt/buizz/repository/server',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '20s',
      env: {
        NODE_ENV: 'production',
        PORT: 5000,
      },
      log_file: '/opt/buizz/logs/buizz-api.log',
      out_file: '/opt/buizz/logs/buizz-api-out.log',
      error_file: '/opt/buizz/logs/buizz-api-error.log',
      merge_logs: true,
    },
    {
      name: 'buizz-admin',
      script: 'server.js',
      cwd: '/opt/buizz/repository/admin',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '20s',
      env: {
        NODE_ENV: 'production',
        ADMIN_PORT: 5001,
      },
      log_file: '/opt/buizz/logs/buizz-admin.log',
      out_file: '/opt/buizz/logs/buizz-admin-out.log',
      error_file: '/opt/buizz/logs/buizz-admin-error.log',
      merge_logs: true,
    },
    {
      name: 'buizz-client',
      script: 'server.js',
      cwd: '/opt/buizz/repository/client',
      interpreter: 'node',
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      autorestart: true,
      restart_delay: 3000,
      max_restarts: 10,
      min_uptime: '20s',
      env: {
        NODE_ENV: 'production',
        PORT: 3000,
        HOSTNAME: '0.0.0.0',
      },
      log_file: '/opt/buizz/logs/buizz-client.log',
      out_file: '/opt/buizz/logs/buizz-client-out.log',
      error_file: '/opt/buizz/logs/buizz-client-error.log',
      merge_logs: true,
    },
  ],
};
