export type DiscoveryKind = "events" | "plays" | "activities";

export type DiscoveryItem = {
  id: string;
  title: string;
  kind: DiscoveryKind;
  category: string;
  genre: string;
  language?: string;
  ageRestriction?: string;
  duration?: string;
  termsConditions?: string;
  date: string;
  dateValue: string;
  time?: string;
  venue: string;
  city: string;
  distanceKm: number;
  price: number;
  priceLabel: string;
  rating: number;
  popularity: number;
  image: string;
  description: string;
  badge: string;
  tags: string[];
  quickFilters: string[];
  href?: string;
  slot?: string;
  sport?: string;
  youtubeUrl?: string;
  instagramUrl?: string;
};

export type DiscoveryConfig = {
  kind: DiscoveryKind;
  route: string;
  topTitle: string;
  topSubtitle: string;
  exploreTitle: string;
  allTitle: string;
  emptyTitle: string;
  emptyDescription: string;
  ctaLabel: string;
  categories: string[];
  sportsTitle?: string;
  sportsCategories?: string[];
  quickFilters: string[];
  primaryFilterLabel: string;
  primaryFilterOptions: string[];
  secondaryFilterLabel?: string;
  secondaryFilterOptions?: string[];
  priceOptions: string[];
  moreFilterOptions: string[];
  items: DiscoveryItem[];
};

export const eventCategories = [
  "Music Events",
  "Nightlife Events",
  "Comedy Events",
  "Sports Events",
  "Performances",
  "Food & Drinks",
  "Fests & Fairs",
  "Social Mixers",
  "Screenings",
  "Fitness Events",
  "Conferences",
  "Open Mics",
  "Spiritual Events",
  "Business Events",
  "Art & Culture",
  "Exhibitions",
  "Kids Events",
  "Tech Events",
  "College Festivals",
];

export const playCategories = [
  "Marathi Plays",
  "Hindi Plays",
  "English Plays",
  "Comedy Plays",
  "Drama Plays",
  "Musical Plays",
  "Experimental Theatre",
  "Kids Plays",
  "Classic Theatre",
  "Storytelling",
  "Poetry & Spoken Word",
  "Open Theatre",
  "Cultural Performances",
];

export const activityCategories = [
  "Game Zones",
  "Theme Parks",
  "Monuments",
  "Water Parks",
  "Kids Play",
  "Workshops",
  "Museums",
  "Adventure",
  "Farm Outings",
  "Games & Quizzes",
  "Art & Craft Workshops",
  "Fitness Activities",
  "Outdoor Activities",
  "Family Activities",
  "Sports",
  "All Activities",
];

const sortOptions = ["Popularity", "Price: Low to High", "Price: High to Low", "Date", "Distance: Near to Far"];
const languageOptions = ["English", "Hindi", "Marathi"];
const standardPriceOptions = ["Free", "₹0–₹500", "₹500–₹2000", "Above ₹2000", "Custom Range"];

const eventItems: DiscoveryItem[] = [
  {
    id: "arijit-live-pune",
    title: "Arijit Singh - Live in Pune",
    kind: "events",
    category: "Music Events",
    genre: "Music",
    language: "Hindi",
    date: "Today, 7:30 PM",
    dateValue: "2026-06-04",
    venue: "Mahalaxmi Lawns",
    city: "Pune",
    distanceKm: 3.8,
    price: 999,
    priceLabel: "₹999 onwards",
    rating: 4.9,
    popularity: 98,
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1400&q=80",
    description: "A stadium-scale music night with soulful hits, premium seating, food counters, and a festival-style crowd experience.",
    badge: "Trending",
    tags: ["Fast Filling", "Verified Events", "Festival Events", "Paid Events"],
    quickFilters: ["Today", "This Week", "This Month", "Near You", "Paid Events"],
    href: "/events/1",
  },
  {
    id: "neon-nights-social",
    title: "Neon Nights Social",
    kind: "events",
    category: "Nightlife Events",
    genre: "Nightlife",
    language: "English",
    date: "Tomorrow, 9:00 PM",
    dateValue: "2026-06-05",
    venue: "High Street Social",
    city: "Pune",
    distanceKm: 5.2,
    price: 699,
    priceLabel: "₹699 onwards",
    rating: 4.7,
    popularity: 90,
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1400&q=80",
    description: "A premium nightlife event with live DJs, neon installations, curated drinks, and a polished social mixer atmosphere.",
    badge: "Selling fast",
    tags: ["Fast Filling", "Outdoor Events", "Verified Events", "Paid Events"],
    quickFilters: ["Tomorrow", "This Week", "Near You", "Paid Events"],
    href: "/events/8",
  },
  {
    id: "zakir-khan-live",
    title: "Zakir Khan - Live",
    kind: "events",
    category: "Comedy Events",
    genre: "Comedy",
    language: "Hindi",
    date: "Sat, 6 June",
    dateValue: "2026-06-06",
    venue: "Symbiosis Auditorium",
    city: "Pune",
    distanceKm: 7.4,
    price: 799,
    priceLabel: "₹799 onwards",
    rating: 4.8,
    popularity: 94,
    image: "https://images.unsplash.com/photo-1527224857830-43a7acc85260?auto=format&fit=crop&w=1400&q=80",
    description: "A sharp stand-up special packed with observational comedy, crowd work, and a premium theatre setup.",
    badge: "Premium seats",
    tags: ["Fast Filling", "Verified Events", "Paid Events"],
    quickFilters: ["This Weekend", "This Week", "This Month", "Paid Events"],
    href: "/events/4",
  },
  {
    id: "champions-turf-league",
    title: "Champions Turf League",
    kind: "events",
    category: "Sports Events",
    genre: "Sports",
    language: "English",
    date: "Sun, 7 June",
    dateValue: "2026-06-07",
    venue: "Shiv Chhatrapati Sports City",
    city: "Pune",
    distanceKm: 9.1,
    price: 349,
    priceLabel: "₹349 onwards",
    rating: 4.5,
    popularity: 76,
    image: "https://images.unsplash.com/photo-1521412644187-c49fa049e84d?auto=format&fit=crop&w=1400&q=80",
    description: "A city sports tournament with live match energy, food stalls, cheering sections, and family-friendly seating.",
    badge: "Weekend pick",
    tags: ["Outdoor Events", "Kids Allowed", "Paid Events"],
    quickFilters: ["This Weekend", "This Week", "This Month", "Paid Events"],
    href: "/events/7",
  },
  {
    id: "mask-movement",
    title: "Mask & Movement Theatre",
    kind: "events",
    category: "Performances",
    genre: "Music",
    language: "Marathi",
    date: "Sun, 7 June",
    dateValue: "2026-06-07",
    venue: "Tilak Smarak Mandir",
    city: "Pune",
    distanceKm: 4.3,
    price: 449,
    priceLabel: "₹449 onwards",
    rating: 4.6,
    popularity: 72,
    image: "https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1400&q=80",
    description: "A curated stage performance blending music, movement, and visual theatre for an intimate cultural evening.",
    badge: "Curated",
    tags: ["Verified Events", "Paid Events"],
    quickFilters: ["This Weekend", "This Week", "This Month", "Paid Events"],
  },
  {
    id: "food-fest-pune",
    title: "Food Fest Pune",
    kind: "events",
    category: "Food & Drinks",
    genre: "Food & Drinks",
    language: "English",
    date: "Fri, 12 June",
    dateValue: "2026-06-12",
    venue: "Phoenix Marketcity",
    city: "Pune",
    distanceKm: 6.7,
    price: 299,
    priceLabel: "₹299 onwards",
    rating: 4.6,
    popularity: 82,
    image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=1400&q=80",
    description: "A premium food and drinks festival with chef counters, tasting menus, live music, and late-evening ambience.",
    badge: "Family pick",
    tags: ["Kids Allowed", "Festival Events", "Verified Events", "Paid Events"],
    quickFilters: ["This Month", "Paid Events"],
  },
  {
    id: "monsoon-fair",
    title: "Monsoon Fests & Fairs",
    kind: "events",
    category: "Fests & Fairs",
    genre: "Music",
    language: "Marathi",
    date: "Sat, 13 June",
    dateValue: "2026-06-13",
    venue: "Amanora Arena",
    city: "Pune",
    distanceKm: 8.4,
    price: 0,
    priceLabel: "Free",
    rating: 4.4,
    popularity: 78,
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1400&q=80",
    description: "A free entry fair with stalls, music corners, family zones, and festival-style discovery across one weekend.",
    badge: "Free entry",
    tags: ["Festival Events", "Kids Allowed", "Outdoor Events", "Free Events"],
    quickFilters: ["This Weekend", "This Month", "Free Events"],
  },
  {
    id: "city-social-mixer",
    title: "City Social Mixer",
    kind: "events",
    category: "Social Mixers",
    genre: "Business",
    language: "English",
    date: "Mon, 15 June",
    dateValue: "2026-06-15",
    venue: "Koregaon Park Studio",
    city: "Pune",
    distanceKm: 2.2,
    price: 499,
    priceLabel: "₹499 onwards",
    rating: 4.5,
    popularity: 70,
    image: "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&w=1400&q=80",
    description: "An easy premium mixer for founders, creators, and city professionals with guided introductions and lounge seating.",
    badge: "Near you",
    tags: ["Verified Events", "Paid Events"],
    quickFilters: ["This Month", "Near You", "Paid Events"],
  },
  {
    id: "indie-film-screening",
    title: "Indie Film Screening",
    kind: "events",
    category: "Screenings",
    genre: "Exhibitions",
    language: "English",
    date: "Tue, 16 June",
    dateValue: "2026-06-16",
    venue: "NFAI Theatre",
    city: "Pune",
    distanceKm: 4.8,
    price: 199,
    priceLabel: "₹199 onwards",
    rating: 4.3,
    popularity: 62,
    image: "https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1400&q=80",
    description: "A curated cinema night with independent shorts, filmmaker notes, and a compact post-screening conversation.",
    badge: "Curated",
    tags: ["Verified Events", "Paid Events"],
    quickFilters: ["This Month", "Paid Events"],
  },
  {
    id: "morning-yoga-wellness",
    title: "Morning Yoga & Wellness",
    kind: "events",
    category: "Fitness Events",
    genre: "Workshops",
    language: "English",
    date: "Wed, 17 June",
    dateValue: "2026-06-17",
    venue: "Osho Garden",
    city: "Pune",
    distanceKm: 1.9,
    price: 0,
    priceLabel: "Free",
    rating: 4.6,
    popularity: 68,
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1400&q=80",
    description: "A calm morning fitness event with guided yoga, breathwork, and a community wellness circle in an outdoor garden.",
    badge: "Free",
    tags: ["Outdoor Events", "Kids Allowed", "Free Events"],
    quickFilters: ["This Month", "Near You", "Free Events"],
  },
  {
    id: "startup-summit-2026",
    title: "Startup Summit 2026",
    kind: "events",
    category: "Conferences",
    genre: "Conferences",
    language: "English",
    date: "Thu, 18 June",
    dateValue: "2026-06-18",
    venue: "ICC Pune",
    city: "Pune",
    distanceKm: 7.8,
    price: 1499,
    priceLabel: "₹1499 onwards",
    rating: 4.7,
    popularity: 86,
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1400&q=80",
    description: "A high-energy business conference with founder talks, pitch rooms, workshops, and curated networking slots.",
    badge: "Featured",
    tags: ["Verified Events", "Online Streaming", "Paid Events"],
    quickFilters: ["This Month", "Paid Events"],
  },
  {
    id: "open-mic-cafe",
    title: "Open Mic Cafe Night",
    kind: "events",
    category: "Open Mics",
    genre: "Open Mics",
    language: "Hindi",
    date: "Fri, 19 June",
    dateValue: "2026-06-19",
    venue: "Viman Nagar Cafe",
    city: "Pune",
    distanceKm: 4.1,
    price: 149,
    priceLabel: "₹149 onwards",
    rating: 4.2,
    popularity: 58,
    image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1400&q=80",
    description: "A cozy open mic for music, poetry, and comedy with friendly stage time and a warm cafe audience.",
    badge: "Creator night",
    tags: ["Verified Events", "Paid Events"],
    quickFilters: ["This Month", "Paid Events"],
  },
  {
    id: "spiritual-satsang",
    title: "Evening Satsang Experience",
    kind: "events",
    category: "Spiritual Events",
    genre: "Spirituality",
    language: "Marathi",
    date: "Sat, 20 June",
    dateValue: "2026-06-20",
    venue: "Ganesh Kala Krida Manch",
    city: "Pune",
    distanceKm: 6.3,
    price: 0,
    priceLabel: "Free",
    rating: 4.5,
    popularity: 66,
    image: "https://images.unsplash.com/photo-1514222134-b57cbb8ce073?auto=format&fit=crop&w=1400&q=80",
    description: "A peaceful spiritual gathering with devotional music, guided reflection, and community seating.",
    badge: "Community",
    tags: ["Kids Allowed", "Free Events", "Verified Events"],
    quickFilters: ["This Weekend", "This Month", "Free Events"],
  },
  {
    id: "business-breakfast",
    title: "Business Breakfast Pune",
    kind: "events",
    category: "Business Events",
    genre: "Business",
    language: "English",
    date: "Mon, 22 June",
    dateValue: "2026-06-22",
    venue: "Baner Business Lounge",
    city: "Pune",
    distanceKm: 5.9,
    price: 899,
    priceLabel: "₹899 onwards",
    rating: 4.4,
    popularity: 64,
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1400&q=80",
    description: "A compact morning business event for owners and operators with focused networking over breakfast.",
    badge: "Invite style",
    tags: ["Verified Events", "Paid Events"],
    quickFilters: ["This Month", "Paid Events"],
  },
  {
    id: "art-culture-walk",
    title: "Art & Culture Walk",
    kind: "events",
    category: "Art & Culture",
    genre: "Exhibitions",
    language: "English",
    date: "Wed, 24 June",
    dateValue: "2026-06-24",
    venue: "Camp Art District",
    city: "Pune",
    distanceKm: 3.1,
    price: 399,
    priceLabel: "₹399 onwards",
    rating: 4.5,
    popularity: 61,
    image: "https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1400&q=80",
    description: "A guided city walk through galleries, public art, and heritage corners with a premium small-group format.",
    badge: "Small group",
    tags: ["Outdoor Events", "Verified Events", "Paid Events"],
    quickFilters: ["This Month", "Near You", "Paid Events"],
  },
  {
    id: "design-expo",
    title: "Design Expo Weekend",
    kind: "events",
    category: "Exhibitions",
    genre: "Exhibitions",
    language: "English",
    date: "Fri, 26 June",
    dateValue: "2026-06-26",
    venue: "JW Convention Hall",
    city: "Pune",
    distanceKm: 8.9,
    price: 2499,
    priceLabel: "₹2499 onwards",
    rating: 4.6,
    popularity: 80,
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1400&q=80",
    description: "A premium exhibition for design, interiors, materials, and creative businesses with verified exhibitors.",
    badge: "Premium",
    tags: ["Verified Events", "Fast Filling", "Paid Events"],
    quickFilters: ["This Month", "Paid Events"],
  },
  {
    id: "kids-carnival",
    title: "Kids Carnival Weekend",
    kind: "events",
    category: "Kids Events",
    genre: "Kids",
    language: "English",
    date: "Sat, 27 June",
    dateValue: "2026-06-27",
    venue: "Seasons Mall",
    city: "Pune",
    distanceKm: 6.6,
    price: 0,
    priceLabel: "Free",
    rating: 4.3,
    popularity: 71,
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1400&q=80",
    description: "A safe and cheerful kids event with game booths, storytelling corners, and parent-friendly amenities.",
    badge: "Kids allowed",
    tags: ["Kids Allowed", "Festival Events", "Free Events"],
    quickFilters: ["This Weekend", "This Month", "Free Events"],
  },
  {
    id: "tech-founders-meet",
    title: "Tech Founders Meet",
    kind: "events",
    category: "Tech Events",
    genre: "Business",
    language: "English",
    date: "Sun, 28 June",
    dateValue: "2026-06-28",
    venue: "Hinjawadi Innovation Hub",
    city: "Pune",
    distanceKm: 11.2,
    price: 599,
    priceLabel: "₹599 onwards",
    rating: 4.5,
    popularity: 67,
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=1400&q=80",
    description: "A founder-focused tech meetup with demo tables, product talks, and operator-led conversations.",
    badge: "Verified",
    tags: ["Verified Events", "Online Streaming", "Paid Events"],
    quickFilters: ["This Month", "Paid Events"],
  },
  {
    id: "college-culture-fest",
    title: "College Culture Fest",
    kind: "events",
    category: "College Festivals",
    genre: "Music",
    language: "Hindi",
    date: "Tue, 30 June",
    dateValue: "2026-06-30",
    venue: "MIT Campus Grounds",
    city: "Pune",
    distanceKm: 10.4,
    price: 299,
    priceLabel: "₹299 onwards",
    rating: 4.4,
    popularity: 74,
    image: "https://images.unsplash.com/photo-1523580494863-6f3031224c94?auto=format&fit=crop&w=1400&q=80",
    description: "A youth culture festival with battle-of-bands, college showcases, food courts, and open-air energy.",
    badge: "Youth pick",
    tags: ["Outdoor Events", "Festival Events", "Paid Events"],
    quickFilters: ["This Month", "Paid Events"],
  },
];

const playItems: DiscoveryItem[] = [
  {
    id: "natsamrat-premium",
    title: "Natsamrat",
    kind: "plays",
    category: "Marathi Plays",
    genre: "Drama",
    language: "Marathi",
    date: "Today, 6:30 PM",
    dateValue: "2026-06-04",
    venue: "Bal Gandharva Rang Mandir",
    city: "Pune",
    distanceKm: 3.2,
    price: 599,
    priceLabel: "₹599 onwards",
    rating: 4.8,
    popularity: 94,
    image: "https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1400&q=80",
    description: "A powerful Marathi theatre classic staged with premium lighting, layered performances, and a full auditorium experience.",
    badge: "Classic",
    tags: ["Premium Shows", "Fast Filling", "Verified Shows", "Paid Plays"],
    quickFilters: ["Today", "This Week", "This Month", "Near You", "Paid Plays"],
  },
  {
    id: "hasya-katta",
    title: "Hasya Katta Live",
    kind: "plays",
    category: "Comedy Plays",
    genre: "Comedy",
    language: "Marathi",
    date: "Tomorrow, 8:00 PM",
    dateValue: "2026-06-05",
    venue: "Yashwantrao Chavan Natyagruha",
    city: "Pune",
    distanceKm: 6.4,
    price: 399,
    priceLabel: "₹399 onwards",
    rating: 4.6,
    popularity: 82,
    image: "https://images.unsplash.com/photo-1517457373958-b7bdd4587205?auto=format&fit=crop&w=1400&q=80",
    description: "A fast-paced comedy play with clean punchlines, family-friendly scenes, and a lively city theatre audience.",
    badge: "Laugh riot",
    tags: ["Family Friendly", "Kids Allowed", "Verified Shows", "Paid Plays"],
    quickFilters: ["Tomorrow", "This Week", "Near You", "Paid Plays"],
  },
  {
    id: "mughal-e-stage",
    title: "Mughal-e-Stage",
    kind: "plays",
    category: "Hindi Plays",
    genre: "Drama",
    language: "Hindi",
    date: "Sat, 6 June",
    dateValue: "2026-06-06",
    venue: "Tilak Smarak Mandir",
    city: "Pune",
    distanceKm: 4.7,
    price: 899,
    priceLabel: "₹899 onwards",
    rating: 4.7,
    popularity: 88,
    image: "https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=1400&q=80",
    description: "A grand Hindi stage production with rich costumes, dramatic sets, and a premium proscenium format.",
    badge: "Premium",
    tags: ["Premium Shows", "Fast Filling", "Verified Shows", "Paid Plays"],
    quickFilters: ["This Weekend", "This Week", "This Month", "Paid Plays"],
  },
  {
    id: "the-glass-room",
    title: "The Glass Room",
    kind: "plays",
    category: "English Plays",
    genre: "English",
    language: "English",
    date: "Sun, 7 June",
    dateValue: "2026-06-07",
    venue: "The Box Studio",
    city: "Pune",
    distanceKm: 2.8,
    price: 699,
    priceLabel: "₹699 onwards",
    rating: 4.5,
    popularity: 76,
    image: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?auto=format&fit=crop&w=1400&q=80",
    description: "A polished English play built around suspense, quiet performances, and an intimate black-box setup.",
    badge: "Black box",
    tags: ["Premium Shows", "Verified Shows", "Paid Plays"],
    quickFilters: ["This Weekend", "This Week", "This Month", "Near You", "Paid Plays"],
  },
  {
    id: "raag-rang",
    title: "Raag Rang Musical",
    kind: "plays",
    category: "Musical Plays",
    genre: "Musical",
    language: "Hindi",
    date: "Fri, 12 June",
    dateValue: "2026-06-12",
    venue: "Annabhau Sathe Auditorium",
    city: "Pune",
    distanceKm: 8.1,
    price: 799,
    priceLabel: "₹799 onwards",
    rating: 4.6,
    popularity: 79,
    image: "https://images.unsplash.com/photo-1465847899084-d164df4dedc6?auto=format&fit=crop&w=1400&q=80",
    description: "A musical theatre evening with live vocals, dramatic staging, and warm family-friendly storytelling.",
    badge: "Musical",
    tags: ["Family Friendly", "Premium Shows", "Verified Shows", "Paid Plays"],
    quickFilters: ["This Month", "Paid Plays"],
  },
  {
    id: "paper-moon",
    title: "Paper Moon Experiments",
    kind: "plays",
    category: "Experimental Theatre",
    genre: "Experimental",
    language: "English",
    date: "Sat, 13 June",
    dateValue: "2026-06-13",
    venue: "Gyaan Adab Centre",
    city: "Pune",
    distanceKm: 5.1,
    price: 499,
    priceLabel: "₹499 onwards",
    rating: 4.4,
    popularity: 69,
    image: "https://images.unsplash.com/photo-1551818255-e6e10975bc17?auto=format&fit=crop&w=1400&q=80",
    description: "Experimental theatre with movement, projection, and nonlinear storytelling for a curious city audience.",
    badge: "Experimental",
    tags: ["Verified Shows", "Paid Plays"],
    quickFilters: ["This Month", "Paid Plays"],
  },
  {
    id: "tiny-tales",
    title: "Tiny Tales Theatre",
    kind: "plays",
    category: "Kids Plays",
    genre: "Kids",
    language: "English",
    date: "Sun, 14 June",
    dateValue: "2026-06-14",
    venue: "Phoenix Kids Stage",
    city: "Pune",
    distanceKm: 6.9,
    price: 0,
    priceLabel: "Free",
    rating: 4.3,
    popularity: 70,
    image: "https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=1400&q=80",
    description: "A bright kids theatre morning with simple stories, interactive moments, and safe family seating.",
    badge: "Kids",
    tags: ["Family Friendly", "Kids Allowed", "Verified Shows", "Free Plays"],
    quickFilters: ["This Weekend", "This Month", "Free Plays"],
  },
  {
    id: "classic-shakespeare",
    title: "Classic Shakespeare Night",
    kind: "plays",
    category: "Classic Theatre",
    genre: "Drama",
    language: "English",
    date: "Tue, 16 June",
    dateValue: "2026-06-16",
    venue: "Nehru Memorial Hall",
    city: "Pune",
    distanceKm: 7.6,
    price: 599,
    priceLabel: "₹599 onwards",
    rating: 4.5,
    popularity: 73,
    image: "https://images.unsplash.com/photo-1503095396549-807759245b35?auto=format&fit=crop&w=1400&q=80",
    description: "A classic theatre evening with crisp staging, period-inspired costume work, and premium auditorium sound.",
    badge: "Classic",
    tags: ["Premium Shows", "Verified Shows", "Paid Plays"],
    quickFilters: ["This Month", "Paid Plays"],
  },
  {
    id: "kahani-circle",
    title: "Kahani Circle",
    kind: "plays",
    category: "Storytelling",
    genre: "Cultural",
    language: "Hindi",
    date: "Thu, 18 June",
    dateValue: "2026-06-18",
    venue: "Koregaon Park Studio",
    city: "Pune",
    distanceKm: 2.4,
    price: 249,
    priceLabel: "₹249 onwards",
    rating: 4.4,
    popularity: 63,
    image: "https://images.unsplash.com/photo-1516280440614-37939bbacd81?auto=format&fit=crop&w=1400&q=80",
    description: "An intimate storytelling night with personal narratives, warm stage lighting, and a small-room theatre feel.",
    badge: "Near you",
    tags: ["Verified Shows", "Paid Plays"],
    quickFilters: ["This Month", "Near You", "Paid Plays"],
  },
  {
    id: "spoken-word-stage",
    title: "Spoken Word Stage",
    kind: "plays",
    category: "Poetry & Spoken Word",
    genre: "Cultural",
    language: "Marathi",
    date: "Fri, 19 June",
    dateValue: "2026-06-19",
    venue: "Viman Nagar Cafe Theatre",
    city: "Pune",
    distanceKm: 4.5,
    price: 199,
    priceLabel: "₹199 onwards",
    rating: 4.2,
    popularity: 59,
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1400&q=80",
    description: "A poetry and spoken-word showcase with compact seating, creator-led performances, and late-evening ambience.",
    badge: "Creator night",
    tags: ["Verified Shows", "Paid Plays"],
    quickFilters: ["This Month", "Paid Plays"],
  },
  {
    id: "open-theatre-weekend",
    title: "Open Theatre Weekend",
    kind: "plays",
    category: "Open Theatre",
    genre: "Experimental",
    language: "Marathi",
    date: "Sat, 20 June",
    dateValue: "2026-06-20",
    venue: "Aundh Amphitheatre",
    city: "Pune",
    distanceKm: 5.7,
    price: 0,
    priceLabel: "Free",
    rating: 4.1,
    popularity: 57,
    image: "https://images.unsplash.com/photo-1515168833906-d2a3b82b302b?auto=format&fit=crop&w=1400&q=80",
    description: "An open-air theatre showcase with short plays, community performers, and a relaxed outdoor stage format.",
    badge: "Outdoor",
    tags: ["Outdoor Stage", "Family Friendly", "Free Plays"],
    quickFilters: ["This Weekend", "This Month", "Free Plays"],
  },
  {
    id: "lok-rang",
    title: "Lok Rang Cultural Stage",
    kind: "plays",
    category: "Cultural Performances",
    genre: "Cultural",
    language: "Marathi",
    date: "Sun, 21 June",
    dateValue: "2026-06-21",
    venue: "Ganesh Kala Krida Manch",
    city: "Pune",
    distanceKm: 6.1,
    price: 399,
    priceLabel: "₹399 onwards",
    rating: 4.6,
    popularity: 75,
    image: "https://images.unsplash.com/photo-1524230659092-07f99a75c013?auto=format&fit=crop&w=1400&q=80",
    description: "A cultural performance evening with folk theatre, music, and a premium stage presentation.",
    badge: "Cultural",
    tags: ["Family Friendly", "Verified Shows", "Paid Plays"],
    quickFilters: ["This Weekend", "This Month", "Paid Plays"],
  },
];

const activityItems: DiscoveryItem[] = [
  {
    id: "vr-game-zone",
    title: "VR Game Zone Pass",
    kind: "activities",
    category: "Game Zones",
    genre: "Game Zones",
    date: "Today",
    dateValue: "2026-06-04",
    venue: "Phoenix Game Arena",
    city: "Pune",
    distanceKm: 2.6,
    price: 399,
    priceLabel: "₹399 onwards",
    rating: 4.7,
    popularity: 90,
    image: "https://images.unsplash.com/photo-1593508512255-86ab42a8e620?auto=format&fit=crop&w=1400&q=80",
    description: "A premium indoor game-zone pass with VR bays, console pods, arcade games, and instant booking slots.",
    badge: "Instant",
    tags: ["Indoor", "Group Activity", "Instant Booking", "Verified Venue"],
    quickFilters: ["Under 5 km", "Today", "Near You", "Indoor"],
    slot: "Slots from 12:00 PM",
  },
  {
    id: "water-park-day",
    title: "Blue Bay Water Park",
    kind: "activities",
    category: "Water Parks",
    genre: "Water Parks",
    date: "Tomorrow",
    dateValue: "2026-06-05",
    venue: "Blue Bay Resort",
    city: "Pune",
    distanceKm: 14.8,
    price: 1199,
    priceLabel: "₹1199 onwards",
    rating: 4.5,
    popularity: 82,
    image: "https://images.unsplash.com/photo-1563911302283-d2bc129e7570?auto=format&fit=crop&w=1400&q=80",
    description: "A full-day water park experience with wave pools, slides, lockers, food counters, and family-friendly access.",
    badge: "Family",
    tags: ["Kids Allowed", "Family Friendly", "Outdoor", "Verified Venue"],
    quickFilters: ["Tomorrow", "This Weekend", "Kids Friendly", "Outdoor"],
    slot: "Open 10:00 AM - 6:00 PM",
  },
  {
    id: "heritage-monument-walk",
    title: "Shaniwar Wada Heritage Walk",
    kind: "activities",
    category: "Monuments",
    genre: "Monuments",
    date: "Sat, 6 June",
    dateValue: "2026-06-06",
    venue: "Shaniwar Wada Gate",
    city: "Pune",
    distanceKm: 3.7,
    price: 249,
    priceLabel: "₹249 onwards",
    rating: 4.6,
    popularity: 76,
    image: "https://images.unsplash.com/photo-1590050752117-238cb0fb12b1?auto=format&fit=crop&w=1400&q=80",
    description: "A guided monument walk with local stories, compact group size, and time for photos at the heritage precinct.",
    badge: "Guided",
    tags: ["Outdoor", "Family Friendly", "Verified Venue"],
    quickFilters: ["Under 5 km", "This Weekend", "Near You", "Outdoor"],
    slot: "Morning and evening slots",
  },
  {
    id: "adventure-rope-course",
    title: "Adventure Rope Course",
    kind: "activities",
    category: "Adventure",
    genre: "Adventure",
    date: "Sun, 7 June",
    dateValue: "2026-06-07",
    venue: "Wakad Adventure Park",
    city: "Pune",
    distanceKm: 8.5,
    price: 699,
    priceLabel: "₹699 onwards",
    rating: 4.6,
    popularity: 84,
    image: "https://images.unsplash.com/photo-1522163182402-834f871fd851?auto=format&fit=crop&w=1400&q=80",
    description: "An outdoor adventure course with rope challenges, safety gear, trained staff, and group activity slots.",
    badge: "Outdoor",
    tags: ["Outdoor", "Group Activity", "Instant Booking", "Verified Venue"],
    quickFilters: ["This Weekend", "Outdoor"],
    slot: "Slots every 90 minutes",
  },
  {
    id: "badminton-court",
    title: "Badminton Court Booking",
    kind: "activities",
    category: "Fitness Activities",
    genre: "Sports",
    sport: "Badminton",
    date: "Today",
    dateValue: "2026-06-04",
    venue: "Kothrud Sports Hub",
    city: "Pune",
    distanceKm: 2.1,
    price: 350,
    priceLabel: "₹350 per hour",
    rating: 4.8,
    popularity: 92,
    image: "https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?auto=format&fit=crop&w=1400&q=80",
    description: "Premium indoor badminton courts with hourly slots, clean flooring, changing rooms, and instant confirmation.",
    badge: "Under 5 km",
    tags: ["Indoor", "Instant Booking", "Verified Venue"],
    quickFilters: ["Under 5 km", "Today", "Near You", "Indoor"],
    slot: "6:00 PM, 7:00 PM, 8:00 PM",
  },
  {
    id: "box-cricket",
    title: "Box Cricket Arena",
    kind: "activities",
    category: "Outdoor Activities",
    genre: "Sports",
    sport: "Box Cricket",
    date: "Tomorrow",
    dateValue: "2026-06-05",
    venue: "Baner Box Cricket",
    city: "Pune",
    distanceKm: 5.8,
    price: 1200,
    priceLabel: "₹1200 per slot",
    rating: 4.7,
    popularity: 88,
    image: "https://images.unsplash.com/photo-1531415074968-036ba1b575da?auto=format&fit=crop&w=1400&q=80",
    description: "A turf box-cricket venue for groups with lighting, scoreboards, and evening team slots.",
    badge: "Group",
    tags: ["Outdoor", "Group Activity", "Instant Booking", "Verified Venue"],
    quickFilters: ["Tomorrow", "Outdoor"],
    slot: "Team slots from 7:00 PM",
  },
  {
    id: "pickleball-club",
    title: "Pickleball Club Slot",
    kind: "activities",
    category: "Fitness Activities",
    genre: "Sports",
    sport: "Pickleball",
    date: "Sat, 6 June",
    dateValue: "2026-06-06",
    venue: "Aundh Pickleball Club",
    city: "Pune",
    distanceKm: 4.2,
    price: 500,
    priceLabel: "₹500 onwards",
    rating: 4.7,
    popularity: 79,
    image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?auto=format&fit=crop&w=1400&q=80",
    description: "Fast-growing pickleball courts with rental gear, beginner-friendly slots, and verified venue amenities.",
    badge: "Trending sport",
    tags: ["Outdoor", "Instant Booking", "Verified Venue"],
    quickFilters: ["Under 5 km", "This Weekend", "Near You", "Outdoor"],
    slot: "Morning and evening slots",
  },
  {
    id: "turf-football",
    title: "Turf Football 5v5",
    kind: "activities",
    category: "Outdoor Activities",
    genre: "Sports",
    sport: "Turf Football",
    date: "Sun, 7 June",
    dateValue: "2026-06-07",
    venue: "Hinjawadi Turf",
    city: "Pune",
    distanceKm: 9.9,
    price: 1600,
    priceLabel: "₹1600 per slot",
    rating: 4.5,
    popularity: 74,
    image: "https://images.unsplash.com/photo-1551958219-acbc608c6377?auto=format&fit=crop&w=1400&q=80",
    description: "A floodlit football turf with 5v5 slots, group bookings, and late-evening availability.",
    badge: "Futsal",
    tags: ["Outdoor", "Group Activity", "Verified Venue"],
    quickFilters: ["This Weekend", "Outdoor"],
    slot: "Late evening slots",
  },
  {
    id: "swimming-lane",
    title: "Swimming Lane Access",
    kind: "activities",
    category: "Fitness Activities",
    genre: "Sports",
    sport: "Swimming",
    date: "Today",
    dateValue: "2026-06-04",
    venue: "Deccan Swim Club",
    city: "Pune",
    distanceKm: 3.3,
    price: 300,
    priceLabel: "₹300 onwards",
    rating: 4.4,
    popularity: 70,
    image: "https://images.unsplash.com/photo-1530549387789-4c1017266635?auto=format&fit=crop&w=1400&q=80",
    description: "Clean swimming lanes with hourly access, changing rooms, coach-supervised timings, and instant booking.",
    badge: "Indoor",
    tags: ["Indoor", "Instant Booking", "Verified Venue"],
    quickFilters: ["Under 5 km", "Today", "Near You", "Indoor"],
    slot: "Slots from 6:00 AM",
  },
  {
    id: "theme-park-pass",
    title: "Theme Park Day Pass",
    kind: "activities",
    category: "Theme Parks",
    genre: "Theme Parks",
    date: "Sat, 13 June",
    dateValue: "2026-06-13",
    venue: "Imagicaa Day Zone",
    city: "Lonavala",
    distanceKm: 58,
    price: 1999,
    priceLabel: "₹1999 onwards",
    rating: 4.5,
    popularity: 86,
    image: "https://images.unsplash.com/photo-1513889961551-628c1e5e2ee9?auto=format&fit=crop&w=1400&q=80",
    description: "A full-day theme park pass with rides, family attractions, food access, and weekend-ready booking slots.",
    badge: "Day trip",
    tags: ["Kids Allowed", "Family Friendly", "Outdoor", "Verified Venue"],
    quickFilters: ["This Weekend", "Kids Friendly", "Outdoor"],
    slot: "Full-day access",
  },
  {
    id: "kids-play-arena",
    title: "Kids Play Arena",
    kind: "activities",
    category: "Kids Play",
    genre: "Kids Play",
    date: "Today",
    dateValue: "2026-06-04",
    venue: "Seasons Kids Zone",
    city: "Pune",
    distanceKm: 4.6,
    price: 450,
    priceLabel: "₹450 onwards",
    rating: 4.6,
    popularity: 78,
    image: "https://images.unsplash.com/photo-1564429238817-393bd4286b2d?auto=format&fit=crop&w=1400&q=80",
    description: "A safe indoor kids play zone with soft play, attendants, parent seating, and short booking windows.",
    badge: "Kids",
    tags: ["Kids Allowed", "Family Friendly", "Indoor", "Instant Booking", "Verified Venue"],
    quickFilters: ["Under 5 km", "Today", "Kids Friendly", "Indoor"],
    slot: "Hourly slots",
  },
  {
    id: "pottery-workshop",
    title: "Pottery Workshop",
    kind: "activities",
    category: "Art & Craft Workshops",
    genre: "Art & Craft Workshops",
    date: "Sun, 14 June",
    dateValue: "2026-06-14",
    venue: "Koregaon Clay Studio",
    city: "Pune",
    distanceKm: 2.9,
    price: 899,
    priceLabel: "₹899 onwards",
    rating: 4.7,
    popularity: 72,
    image: "https://images.unsplash.com/photo-1493106819501-66d381c466f1?auto=format&fit=crop&w=1400&q=80",
    description: "A hands-on pottery workshop with guided making, glazing basics, and a premium studio setup.",
    badge: "Workshop",
    tags: ["Indoor", "Group Activity", "Verified Venue"],
    quickFilters: ["Under 5 km", "This Weekend", "Near You", "Indoor"],
    slot: "11:00 AM and 4:00 PM",
  },
  {
    id: "museum-after-hours",
    title: "Museum After Hours",
    kind: "activities",
    category: "Museums",
    genre: "Museums",
    date: "Fri, 19 June",
    dateValue: "2026-06-19",
    venue: "Raja Dinkar Kelkar Museum",
    city: "Pune",
    distanceKm: 3.5,
    price: 199,
    priceLabel: "₹199 onwards",
    rating: 4.4,
    popularity: 65,
    image: "https://images.unsplash.com/photo-1566127992631-137a642a90f4?auto=format&fit=crop&w=1400&q=80",
    description: "An after-hours museum visit with guided highlights, quiet galleries, and a compact cultural route.",
    badge: "Culture",
    tags: ["Indoor", "Family Friendly", "Verified Venue"],
    quickFilters: ["Under 5 km", "Near You", "Indoor"],
    slot: "Evening guided slots",
  },
  {
    id: "farm-outing",
    title: "Weekend Farm Outing",
    kind: "activities",
    category: "Farm Outings",
    genre: "Farm Outings",
    date: "Sat, 20 June",
    dateValue: "2026-06-20",
    venue: "Mulshi Farm Trails",
    city: "Mulshi",
    distanceKm: 31,
    price: 1299,
    priceLabel: "₹1299 onwards",
    rating: 4.5,
    popularity: 73,
    image: "https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1400&q=80",
    description: "A family farm outing with meals, guided trails, outdoor games, and group-friendly rural experiences.",
    badge: "Family",
    tags: ["Kids Allowed", "Family Friendly", "Outdoor", "Group Activity", "Verified Venue"],
    quickFilters: ["This Weekend", "Kids Friendly", "Outdoor"],
    slot: "Full-day outing",
  },
  {
    id: "quiz-night",
    title: "Games & Quiz Night",
    kind: "activities",
    category: "Games & Quizzes",
    genre: "Games & Quizzes",
    date: "Thu, 25 June",
    dateValue: "2026-06-25",
    venue: "Baner Social Club",
    city: "Pune",
    distanceKm: 5.4,
    price: 299,
    priceLabel: "₹299 onwards",
    rating: 4.3,
    popularity: 61,
    image: "https://images.unsplash.com/photo-1610890716171-6b1bb98ffd09?auto=format&fit=crop&w=1400&q=80",
    description: "A premium pub-quiz and games night with teams, prizes, table reservations, and a friendly host.",
    badge: "Teams",
    tags: ["Indoor", "Group Activity", "Instant Booking", "Verified Venue"],
    quickFilters: ["Indoor"],
    slot: "Starts 8:00 PM",
  },
];

export const eventsDiscoveryConfig: DiscoveryConfig = {
  kind: "events",
  route: "/events",
  topTitle: "Your Next Ticket Starts Here",
  topSubtitle: "Trending events happening around you.",
  exploreTitle: "Explore Events",
  allTitle: "All Events",
  emptyTitle: "No events match these filters",
  emptyDescription: "Try a different category, quick filter, or search term to discover more Buizz events.",
  ctaLabel: "Book Ticket",
  categories: eventCategories,
  quickFilters: ["Today", "Tomorrow", "This Weekend", "This Week", "This Month", "Near You", "Free Events", "Paid Events"],
  primaryFilterLabel: "Genre",
  primaryFilterOptions: ["Music", "Comedy", "Nightlife", "Business", "Spirituality", "Exhibitions", "Food & Drinks", "Open Mics", "Sports", "Workshops", "Conferences", "Kids"],
  secondaryFilterLabel: "Language",
  secondaryFilterOptions: languageOptions,
  priceOptions: standardPriceOptions,
  moreFilterOptions: ["Outdoor Events", "Fast Filling", "Kids Allowed", "Online Streaming", "Festival Events", "Verified Events"],
  items: eventItems,
};

export const playsDiscoveryConfig: DiscoveryConfig = {
  kind: "plays",
  route: "/plays",
  topTitle: "Experience Stories Live",
  topSubtitle: "Popular plays and theatre experiences near you.",
  exploreTitle: "Explore Plays",
  allTitle: "All Plays",
  emptyTitle: "No plays match these filters",
  emptyDescription: "Adjust the theatre category, language, price, or quick filter to find more shows.",
  ctaLabel: "Book Ticket",
  categories: playCategories,
  quickFilters: ["Today", "Tomorrow", "This Weekend", "This Week", "This Month", "Near You", "Free Plays", "Paid Plays"],
  primaryFilterLabel: "Genre",
  primaryFilterOptions: ["Marathi", "Hindi", "English", "Comedy", "Drama", "Musical", "Kids", "Experimental", "Cultural"],
  secondaryFilterLabel: "Language",
  secondaryFilterOptions: ["Marathi", "Hindi", "English"],
  priceOptions: standardPriceOptions,
  moreFilterOptions: ["Family Friendly", "Kids Allowed", "Premium Shows", "Fast Filling", "Outdoor Stage", "Verified Shows"],
  items: playItems,
};

export const activitiesDiscoveryConfig: DiscoveryConfig = {
  kind: "activities",
  route: "/activities",
  topTitle: "Explore Activities Around You",
  topSubtitle: "Fun activities, sports, adventure, and experiences near you.",
  exploreTitle: "Explore Activities",
  allTitle: "All Activities",
  emptyTitle: "No activities match these filters",
  emptyDescription: "Try another activity type, sport, distance, or date filter to see more venues.",
  ctaLabel: "Book Now",
  categories: activityCategories,
  quickFilters: ["Under 5 km", "Today", "Tomorrow", "This Weekend", "Near You", "Kids Friendly", "Outdoor", "Indoor"],
  primaryFilterLabel: "Activity Type",
  primaryFilterOptions: ["Game Zones", "Theme Parks", "Monuments", "Water Parks", "Kids Play", "Workshops", "Museums", "Adventure", "Farm Outings", "Games & Quizzes", "Art & Craft Workshops", "Sports"],
  secondaryFilterLabel: "Sports",
  secondaryFilterOptions: ["Badminton", "Box Cricket", "Pickleball", "Turf Football", "Swimming", "Table Tennis", "Cricket", "Football"],
  priceOptions: standardPriceOptions,
  moreFilterOptions: ["Kids Allowed", "Family Friendly", "Outdoor", "Indoor", "Group Activity", "Instant Booking", "Verified Venue"],
  items: activityItems,
};

export const sortOptionsForDiscovery = sortOptions;

export const allDiscoveryItems = [...eventItems, ...playItems, ...activityItems];

export function findDiscoveryItemById(id: string, kind?: DiscoveryKind) {
  const pool = kind ? allDiscoveryItems.filter((item) => item.kind === kind) : allDiscoveryItems;
  return pool.find((item) => item.id === id || item.href?.split("/").pop() === id) ?? null;
}

export function slugifyCategory(value: string) {
  return value
    .toLowerCase()
    .replace(/&/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function resolveCategoryFromSlug(config: DiscoveryConfig, slug: string) {
  return config.categories.find((category) => slugifyCategory(category) === slug);
}

export function getCategorySubtitle(kind: DiscoveryKind, category: string) {
  if (kind === "events") {
    if (category === "Music Events") return "Discover concerts, live gigs, music festivals, open mics, and performances near you.";
    return `Discover ${category.toLowerCase()}, premium city plans, and curated experiences near you.`;
  }

  if (kind === "plays") {
    if (category === "Marathi Plays") return "Explore Marathi theatre, drama, comedy plays, and cultural performances near you.";
    return `Explore ${category.toLowerCase()}, theatre performances, and live stage experiences near you.`;
  }

  if (category === "Game Zones") return "Find gaming zones, arcades, indoor games, and fun experiences near you.";
  if (category === "Sports") return "Book sports venues, courts, nets, pools, and active experiences near you.";
  return `Find ${category.toLowerCase()}, bookable slots, and fun experiences near you.`;
}

export function getItemsForCategory(config: DiscoveryConfig, category: string) {
  if (category === "All Activities") return config.items;

  const exactItems = config.items.filter((item) => {
    if (item.category === category || item.genre === category || item.sport === category) return true;
    if (item.tags.includes(category)) return true;
    if (category === "Sports") return item.genre === "Sports" || Boolean(item.sport);
    return false;
  });

  return exactItems;
}

function inferEventGenre(category: string, fallback: string) {
  const genreMap: Record<string, string> = {
    "Music Events": "Music",
    "Comedy Events": "Comedy",
    "Nightlife Events": "Nightlife",
    "Business Events": "Business",
    "Spiritual Events": "Spirituality",
    "Food & Drinks": "Food & Drinks",
    "Open Mics": "Open Mics",
    "Sports Events": "Sports",
    Conferences: "Conferences",
    "Kids Events": "Kids",
    Exhibitions: "Exhibitions",
  };

  return genreMap[category] ?? fallback;
}

function inferPlayGenre(category: string, fallback: string) {
  if (category.includes("Comedy")) return "Comedy";
  if (category.includes("Musical")) return "Musical";
  if (category.includes("Kids")) return "Kids";
  if (category.includes("Experimental")) return "Experimental";
  if (category.includes("Cultural") || category.includes("Storytelling") || category.includes("Poetry")) return "Cultural";
  return category.includes("Drama") ? "Drama" : fallback;
}

function inferActivityGenre(category: string, fallback: string) {
  if (category === "Sports") return "Sports";
  return category === "All Activities" ? fallback : category;
}
